<?php
/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_dibs_invoice_paybybill_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['commerce_dibs_invoice_paybybill'] = array(
    'title' => t('DIBS invoice PayByBill'),
    'description' => t('Invoice payment using the DIBS PayByBill provider.'),
    'display_title' => t('DIBS invoice PayByBill'),
    'offsite' => TRUE,
  );
  return $payment_methods;
}
// @todo, settings for label!
/**
 * Payment method callback: settings form.
 */
function commerce_dibs_invoice_paybybill_settings_form($settings = NULL) {
  $form = array();
  $form['info']['#markup'] = l(t('Setup commerce dibs invoice'), 'admin/config/payment/dibs/edit/commerce_dibs_invoice_paybybill/commerce_dibs_invoice_paybybill');
  $form += _commerce_dibs_invoice_settings_form($settings);
  return $form;
}

/**
 * Payment method callback: submit form.
 */
function commerce_dibs_invoice_paybybill_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  return _commerce_dibs_invoice_submit_form($payment_method, $pane_values, $checkout_pane, $order);
}

/**
 * Payment method callback: submit form submit handler.
 */

function commerce_dibs_invoice_paybybill_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge) {
  _commerce_dibs_invoice_submit_form_submit($payment_method, $pane_form, $pane_values, $order, $charge);
}

/**
 * Payment method callback: redirect form, a wrapper around the module's general
 *   use function for building a WPS form.
 */

function commerce_dibs_invoice_paybybill_redirect_form($form, &$form_state, $order, $payment_method) {
  $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

  // Prepare the DIBS payment
  $data = _commerce_dibs_dibs_transaction_data($order, 'commerce_dibs_invoice', 'commerce_dibs_invoice');
  $hash = dibs_payment_prepare($data, FALSE);
  $dibs_transaction = dibs_transaction_hash_load($hash);

  // Prepare the commerce transaction

  $transaction = _commerce_dibs_commerce_transaction($order_wrapper, $payment_method, $dibs_transaction['tid']);

  $settings = dibs_load_settings('commerce_dibs_invoice', 'commerce_dibs_invoice');
  $settings['auto_submit'] = 1;

  module_load_include('inc', 'dibs', 'dibs.frontend');

  $dibs_params = _commerce_dibs_commerce_order_dibs_data($order_wrapper) +
    _commerce_dibs_invoice_dibs_data($order_wrapper, $payment_method);

  $dibs_params['payType'] = $settings['general']['test_mode'] ? DIBS_INVOICE_PAYBYBILL_TEST : DIBS_INVOICE_PAYBYBILL;

  return drupal_get_form('dibs_frontend_redirect_form', $settings, $dibs_transaction, $dibs_params);
}

